# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/trusseditor/forms/editcoordinates/editcoordinates.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_EditCoordinatesDialog(object):
    def setupUi(self, EditCoordinatesDialog):
        EditCoordinatesDialog.setObjectName("EditCoordinatesDialog")
        EditCoordinatesDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        EditCoordinatesDialog.resize(202, 118)
        EditCoordinatesDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(EditCoordinatesDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xCoordinate = QtWidgets.QLineEdit(parent=EditCoordinatesDialog)
        self.xCoordinate.setObjectName("xCoordinate")
        self.verticalLayout.addWidget(self.xCoordinate)
        self.yCoordinate = QtWidgets.QLineEdit(parent=EditCoordinatesDialog)
        font = QtGui.QFont()
        font.setFamily(".AppleSystemUIFont")
        self.yCoordinate.setFont(font)
        self.yCoordinate.setObjectName("yCoordinate")
        self.verticalLayout.addWidget(self.yCoordinate)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doneButton = QtWidgets.QPushButton(parent=EditCoordinatesDialog)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout.addWidget(self.doneButton)
        self.cancelButton = QtWidgets.QPushButton(parent=EditCoordinatesDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(EditCoordinatesDialog)
        QtCore.QMetaObject.connectSlotsByName(EditCoordinatesDialog)

    def retranslateUi(self, EditCoordinatesDialog):
        _translate = QtCore.QCoreApplication.translate
        EditCoordinatesDialog.setWindowTitle(_translate("EditCoordinatesDialog", "Edit Coordinates"))
        self.xCoordinate.setPlaceholderText(_translate("EditCoordinatesDialog", "X Coordinate"))
        self.yCoordinate.setPlaceholderText(_translate("EditCoordinatesDialog", "Y Coordinate"))
        self.doneButton.setText(_translate("EditCoordinatesDialog", "Done"))
        self.cancelButton.setText(_translate("EditCoordinatesDialog", "Cancel"))
