# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/trusseditor/supports/supportAddForm.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_addSupportForm(object):
    def setupUi(self, addSupportForm):
        addSupportForm.setObjectName("addSupportForm")
        addSupportForm.resize(500, 100)
        self.verticalLayout = QtWidgets.QVBoxLayout(addSupportForm)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_type = QtWidgets.QComboBox(parent=addSupportForm)
        self.select_type.setObjectName("select_type")
        self.select_type.addItem("")
        self.select_type.addItem("")
        self.select_type.addItem("")
        self.select_type.addItem("")
        self.horizontalLayout.addWidget(self.select_type)
        self.select_joint = QtWidgets.QComboBox(parent=addSupportForm)
        self.select_joint.setObjectName("select_joint")
        self.select_joint.addItem("")
        self.horizontalLayout.addWidget(self.select_joint)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.supportButton = QtWidgets.QPushButton(parent=addSupportForm)
        self.supportButton.setObjectName("supportButton")
        self.verticalLayout.addWidget(self.supportButton)

        self.retranslateUi(addSupportForm)
        QtCore.QMetaObject.connectSlotsByName(addSupportForm)

    def retranslateUi(self, addSupportForm):
        _translate = QtCore.QCoreApplication.translate
        addSupportForm.setWindowTitle(_translate("addSupportForm", "Add Widget"))
        self.select_type.setItemText(0, _translate("addSupportForm", "Select Type"))
        self.select_type.setItemText(1, _translate("addSupportForm", "Fixed Pin"))
        self.select_type.setItemText(2, _translate("addSupportForm", "Roller Pin"))
        self.select_type.setItemText(3, _translate("addSupportForm", "Fixed"))
        self.select_joint.setItemText(0, _translate("addSupportForm", "Select Joint:"))
        self.supportButton.setText(_translate("addSupportForm", "Add Support"))
