# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/src/widgets/contextmenus/startmenu/startpage.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_StartPage(object):
    def setupUi(self, StartPage):
        StartPage.setObjectName("StartPage")
        StartPage.resize(459, 454)
        self.verticalLayout = QtWidgets.QVBoxLayout(StartPage)
        self.verticalLayout.setObjectName("verticalLayout")
        self.welcomLabel = QtWidgets.QLabel(parent=StartPage)
        self.welcomLabel.setObjectName("welcomLabel")
        self.verticalLayout.addWidget(self.welcomLabel)
        self.line = QtWidgets.QFrame(parent=StartPage)
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newLabel = QtWidgets.QLabel(parent=StartPage)
        self.newLabel.setObjectName("newLabel")
        self.horizontalLayout.addWidget(self.newLabel)
        self.newButton = QtWidgets.QPushButton(parent=StartPage)
        self.newButton.setObjectName("newButton")
        self.horizontalLayout.addWidget(self.newButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.openLabel = QtWidgets.QLabel(parent=StartPage)
        self.openLabel.setObjectName("openLabel")
        self.horizontalLayout_2.addWidget(self.openLabel)
        self.openButton = QtWidgets.QPushButton(parent=StartPage)
        self.openButton.setObjectName("openButton")
        self.horizontalLayout_2.addWidget(self.openButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.docsLabel = QtWidgets.QLabel(parent=StartPage)
        self.docsLabel.setObjectName("docsLabel")
        self.horizontalLayout_3.addWidget(self.docsLabel)
        self.docsButton = QtWidgets.QPushButton(parent=StartPage)
        self.docsButton.setObjectName("docsButton")
        self.horizontalLayout_3.addWidget(self.docsButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(StartPage)
        QtCore.QMetaObject.connectSlotsByName(StartPage)

    def retranslateUi(self, StartPage):
        _translate = QtCore.QCoreApplication.translate
        StartPage.setWindowTitle(_translate("StartPage", "Start Page"))
        self.welcomLabel.setText(_translate("StartPage", "Welcom to the pytruss GUI!"))
        self.newLabel.setText(_translate("StartPage", "Create a new truss:"))
        self.newButton.setText(_translate("StartPage", "New"))
        self.openLabel.setText(_translate("StartPage", "Open a truss:"))
        self.openButton.setText(_translate("StartPage", "Open"))
        self.docsLabel.setText(_translate("StartPage", "See the docs:"))
        self.docsButton.setText(_translate("StartPage", "Help"))
