# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/trusseditor/forms/optimizer/optimize.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        Dialog.resize(645, 478)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setObjectName("tabWidget")
        self.optimize = QtWidgets.QWidget()
        self.optimize.setObjectName("optimize")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.optimize)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.trainingControls = QtWidgets.QGroupBox(parent=self.optimize)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.trainingControls.sizePolicy().hasHeightForWidth())
        self.trainingControls.setSizePolicy(sizePolicy)
        self.trainingControls.setObjectName("trainingControls")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.trainingControls)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.controlButton = QtWidgets.QHBoxLayout()
        self.controlButton.setObjectName("controlButton")
        self.startButton = QtWidgets.QPushButton(parent=self.trainingControls)
        self.startButton.setObjectName("startButton")
        self.controlButton.addWidget(self.startButton)
        self.stopButton = QtWidgets.QPushButton(parent=self.trainingControls)
        self.stopButton.setObjectName("stopButton")
        self.controlButton.addWidget(self.stopButton)
        self.saveButton = QtWidgets.QPushButton(parent=self.trainingControls)
        self.saveButton.setObjectName("saveButton")
        self.controlButton.addWidget(self.saveButton)
        self.verticalLayout_4.addLayout(self.controlButton)
        self.progressBar = QtWidgets.QProgressBar(parent=self.trainingControls)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_4.addWidget(self.progressBar)
        self.verticalLayout_3.addWidget(self.trainingControls)
        self.tabWidget.addTab(self.optimize, "")
        self.settings = QtWidgets.QWidget()
        self.settings.setObjectName("settings")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.settings)
        self.verticalLayout.setObjectName("verticalLayout")
        self.trainingSetting = QtWidgets.QWidget(parent=self.settings)
        self.trainingSetting.setObjectName("trainingSetting")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.trainingSetting)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.optimizationSettings = QtWidgets.QGroupBox(
            parent=self.trainingSetting)
        self.optimizationSettings.setObjectName("optimizationSettings")
        self.formLayout_2 = QtWidgets.QFormLayout(self.optimizationSettings)
        self.formLayout_2.setObjectName("formLayout_2")
        self.epochsLabel = QtWidgets.QLabel(parent=self.optimizationSettings)
        self.epochsLabel.setObjectName("epochsLabel")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.epochsLabel)
        self.epochsSpinBox = QtWidgets.QSpinBox(
            parent=self.optimizationSettings)
        self.epochsSpinBox.setMaximum(999999999)
        self.epochsSpinBox.setSingleStep(100)
        self.epochsSpinBox.setObjectName("epochsSpinBox")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.epochsSpinBox)
        self.updateMetricsIntervalLabel = QtWidgets.QLabel(
            parent=self.optimizationSettings)
        self.updateMetricsIntervalLabel.setObjectName(
            "updateMetricsIntervalLabel")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.updateMetricsIntervalLabel)
        self.updateMetricsIntervalSpinBox = QtWidgets.QSpinBox(
            parent=self.optimizationSettings)
        self.updateMetricsIntervalSpinBox.setMaximum(999999999)
        self.updateMetricsIntervalSpinBox.setSingleStep(10)
        self.updateMetricsIntervalSpinBox.setObjectName(
            "updateMetricsIntervalSpinBox")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.updateMetricsIntervalSpinBox)
        self.constraintAggressionLabel = QtWidgets.QLabel(
            parent=self.optimizationSettings)
        self.constraintAggressionLabel.setObjectName(
            "constraintAggressionLabel")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.constraintAggressionLabel)
        self.constraintAggressionLineEdit = QtWidgets.QLineEdit(
            parent=self.optimizationSettings)
        self.constraintAggressionLineEdit.setObjectName(
            "constraintAggressionLineEdit")
        self.formLayout_2.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.constraintAggressionLineEdit)
        self.learningRateLabel = QtWidgets.QLabel(
            parent=self.optimizationSettings)
        self.learningRateLabel.setObjectName("learningRateLabel")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.learningRateLabel)
        self.learningRateLineEdit = QtWidgets.QLineEdit(
            parent=self.optimizationSettings)
        self.learningRateLineEdit.setObjectName("learningRateLineEdit")
        self.formLayout_2.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.learningRateLineEdit)
        self.optimizerLabel = QtWidgets.QLabel(
            parent=self.optimizationSettings)
        self.optimizerLabel.setObjectName("optimizerLabel")
        self.formLayout_2.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.optimizerLabel)
        self.optimizerComboBox = QtWidgets.QComboBox(
            parent=self.optimizationSettings)
        self.optimizerComboBox.setObjectName("optimizerComboBox")
        self.optimizerComboBox.addItem("")
        self.optimizerComboBox.addItem("")
        self.formLayout_2.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.optimizerComboBox)
        self.frameRateLabel = QtWidgets.QLabel(
            parent=self.optimizationSettings)
        self.frameRateLabel.setObjectName("frameRateLabel")
        self.formLayout_2.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.frameRateLabel)
        self.frameRateSpinBox = QtWidgets.QSpinBox(
            parent=self.optimizationSettings)
        self.frameRateSpinBox.setMaximum(30)
        self.frameRateSpinBox.setObjectName("frameRateSpinBox")
        self.formLayout_2.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.frameRateSpinBox)
        self.horizontalLayout.addWidget(self.optimizationSettings)
        self.constraintSettings = QtWidgets.QGroupBox(
            parent=self.trainingSetting)
        self.constraintSettings.setObjectName("constraintSettings")
        self.formLayout = QtWidgets.QFormLayout(self.constraintSettings)
        self.formLayout.setObjectName("formLayout")
        self.memberCostLabel = QtWidgets.QLabel(parent=self.constraintSettings)
        self.memberCostLabel.setObjectName("memberCostLabel")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.memberCostLabel)
        self.memberCostLineEdit = QtWidgets.QLineEdit(
            parent=self.constraintSettings)
        self.memberCostLineEdit.setObjectName("memberCostLineEdit")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.memberCostLineEdit)
        self.jointCostLabel = QtWidgets.QLabel(parent=self.constraintSettings)
        self.jointCostLabel.setObjectName("jointCostLabel")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.jointCostLabel)
        self.jointCostLineEdit = QtWidgets.QLineEdit(
            parent=self.constraintSettings)
        self.jointCostLineEdit.setObjectName("jointCostLineEdit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.jointCostLineEdit)
        self.minMemberLenghtLabel = QtWidgets.QLabel(
            parent=self.constraintSettings)
        self.minMemberLenghtLabel.setObjectName("minMemberLenghtLabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.minMemberLenghtLabel)
        self.minMemberLenghtLineEdit = QtWidgets.QLineEdit(
            parent=self.constraintSettings)
        self.minMemberLenghtLineEdit.setObjectName("minMemberLenghtLineEdit")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.minMemberLenghtLineEdit)
        self.maxMemberLengthLabel = QtWidgets.QLabel(
            parent=self.constraintSettings)
        self.maxMemberLengthLabel.setObjectName("maxMemberLengthLabel")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.maxMemberLengthLabel)
        self.maxMemberLengthLineEdit = QtWidgets.QLineEdit(
            parent=self.constraintSettings)
        self.maxMemberLengthLineEdit.setObjectName("maxMemberLengthLineEdit")
        self.formLayout.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.maxMemberLengthLineEdit)
        self.maxTensileForceLabel = QtWidgets.QLabel(
            parent=self.constraintSettings)
        self.maxTensileForceLabel.setObjectName("maxTensileForceLabel")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.maxTensileForceLabel)
        self.maxTensileForceLineEdit = QtWidgets.QLineEdit(
            parent=self.constraintSettings)
        self.maxTensileForceLineEdit.setObjectName("maxTensileForceLineEdit")
        self.formLayout.setWidget(
            4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.maxTensileForceLineEdit)
        self.maxCompressiveForceLabel = QtWidgets.QLabel(
            parent=self.constraintSettings)
        self.maxCompressiveForceLabel.setObjectName("maxCompressiveForceLabel")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.maxCompressiveForceLabel)
        self.maxCompressiveForceLineEdit = QtWidgets.QLineEdit(
            parent=self.constraintSettings)
        self.maxCompressiveForceLineEdit.setObjectName(
            "maxCompressiveForceLineEdit")
        self.formLayout.setWidget(
            5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.maxCompressiveForceLineEdit)
        self.horizontalLayout.addWidget(self.constraintSettings)
        self.verticalLayout.addWidget(self.trainingSetting)
        self.otherSettings = QtWidgets.QGroupBox(parent=self.settings)
        self.otherSettings.setTitle("")
        self.otherSettings.setFlat(False)
        self.otherSettings.setCheckable(False)
        self.otherSettings.setObjectName("otherSettings")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.otherSettings)
        self.verticalLayout_5.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.saveSettings = QtWidgets.QHBoxLayout()
        self.saveSettings.setObjectName("saveSettings")
        self.saveFrequencyLabel = QtWidgets.QLabel(parent=self.otherSettings)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.saveFrequencyLabel.sizePolicy().hasHeightForWidth())
        self.saveFrequencyLabel.setSizePolicy(sizePolicy)
        self.saveFrequencyLabel.setObjectName("saveFrequencyLabel")
        self.saveSettings.addWidget(self.saveFrequencyLabel)
        self.saveFrequencySpinBox = QtWidgets.QSpinBox(
            parent=self.otherSettings)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.saveFrequencySpinBox.sizePolicy().hasHeightForWidth())
        self.saveFrequencySpinBox.setSizePolicy(sizePolicy)
        self.saveFrequencySpinBox.setMaximum(999999999)
        self.saveFrequencySpinBox.setSingleStep(100)
        self.saveFrequencySpinBox.setObjectName("saveFrequencySpinBox")
        self.saveSettings.addWidget(self.saveFrequencySpinBox)
        self.savePathLabel = QtWidgets.QLabel(parent=self.otherSettings)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.savePathLabel.sizePolicy().hasHeightForWidth())
        self.savePathLabel.setSizePolicy(sizePolicy)
        self.savePathLabel.setObjectName("savePathLabel")
        self.saveSettings.addWidget(self.savePathLabel)
        self.savePathSelection = QtWidgets.QLabel(parent=self.otherSettings)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.savePathSelection.sizePolicy().hasHeightForWidth())
        self.savePathSelection.setSizePolicy(sizePolicy)
        self.savePathSelection.setAutoFillBackground(True)
        self.savePathSelection.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.savePathSelection.setText("")
        self.savePathSelection.setIndent(0)
        self.savePathSelection.setObjectName("savePathSelection")
        self.saveSettings.addWidget(self.savePathSelection)
        self.selectPathButton = QtWidgets.QPushButton(
            parent=self.otherSettings)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.selectPathButton.sizePolicy().hasHeightForWidth())
        self.selectPathButton.setSizePolicy(sizePolicy)
        self.selectPathButton.setObjectName("selectPathButton")
        self.saveSettings.addWidget(self.selectPathButton)
        self.verticalLayout_5.addLayout(self.saveSettings)
        self.buttonMenu = QtWidgets.QHBoxLayout()
        self.buttonMenu.setObjectName("buttonMenu")
        self.applySettingsButton = QtWidgets.QPushButton(
            parent=self.otherSettings)
        self.applySettingsButton.setObjectName("applySettingsButton")
        self.buttonMenu.addWidget(self.applySettingsButton)
        self.resetSettingsButton = QtWidgets.QPushButton(
            parent=self.otherSettings)
        self.resetSettingsButton.setObjectName("resetSettingsButton")
        self.buttonMenu.addWidget(self.resetSettingsButton)
        self.verticalLayout_5.addLayout(self.buttonMenu)
        self.verticalLayout.addWidget(self.otherSettings)
        self.tabWidget.addTab(self.settings, "")
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Optimize"))
        self.startButton.setText(_translate("Dialog", "Start"))
        self.stopButton.setText(_translate("Dialog", "Stop"))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.optimize), _translate("Dialog", "Optimize"))
        self.optimizationSettings.setTitle(
            _translate("Dialog", "Optimization"))
        self.epochsLabel.setText(_translate("Dialog", "Epochs"))
        self.updateMetricsIntervalLabel.setText(
            _translate("Dialog", "Update Metrics Interval"))
        self.constraintAggressionLabel.setText(
            _translate("Dialog", "Constraint Aggression"))
        self.learningRateLabel.setText(_translate("Dialog", "Learning Rate"))
        self.optimizerLabel.setText(_translate("Dialog", "Optimizer"))
        self.optimizerComboBox.setItemText(0, _translate("Dialog", "SGD"))
        self.optimizerComboBox.setItemText(1, _translate("Dialog", "Adam"))
        self.frameRateLabel.setText(_translate("Dialog", "Frame Rate"))
        self.constraintSettings.setTitle(_translate("Dialog", "Constraints"))
        self.memberCostLabel.setText(_translate("Dialog", "Member Cost"))
        self.jointCostLabel.setText(_translate("Dialog", "Joint Cost"))
        self.minMemberLenghtLabel.setText(
            _translate("Dialog", "Min Member Lenght"))
        self.maxMemberLengthLabel.setText(
            _translate("Dialog", "Max Member Length"))
        self.maxTensileForceLabel.setText(
            _translate("Dialog", "Max Tensile Force"))
        self.maxCompressiveForceLabel.setText(
            _translate("Dialog", "Max Compressive Force"))
        self.saveFrequencyLabel.setText(_translate("Dialog", "Save Frequency"))
        self.savePathLabel.setText(_translate("Dialog", "Save Path:"))
        self.selectPathButton.setText(_translate("Dialog", "Path..."))
        self.applySettingsButton.setText(_translate("Dialog", "Apply"))
        self.resetSettingsButton.setText(_translate("Dialog", "Reset"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(
            self.settings), _translate("Dialog", "Settings"))
