# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/trusseditor/forms/addforce/addforce.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_addForceForm(object):
    def setupUi(self, addForceForm):
        addForceForm.setObjectName("addForceForm")
        addForceForm.resize(500, 100)
        addForceForm.setMinimumSize(QtCore.QSize(0, 1))
        self.verticalLayout = QtWidgets.QVBoxLayout(addForceForm)
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.x_component = QtWidgets.QLineEdit(parent=addForceForm)
        self.x_component.setObjectName("x_component")
        self.horizontalLayout.addWidget(self.x_component)
        self.y_component = QtWidgets.QLineEdit(parent=addForceForm)
        self.y_component.setInputMethodHints(QtCore.Qt.InputMethodHint.ImhNone)
        self.y_component.setInputMask("")
        self.y_component.setClearButtonEnabled(False)
        self.y_component.setObjectName("y_component")
        self.horizontalLayout.addWidget(self.y_component)
        self.select_joint = QtWidgets.QComboBox(parent=addForceForm)
        self.select_joint.setObjectName("select_joint")
        self.select_joint.addItem("")
        self.horizontalLayout.addWidget(self.select_joint)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.forceButton = QtWidgets.QPushButton(parent=addForceForm)
        self.forceButton.setObjectName("forceButton")
        self.verticalLayout.addWidget(self.forceButton)

        self.retranslateUi(addForceForm)
        QtCore.QMetaObject.connectSlotsByName(addForceForm)

    def retranslateUi(self, addForceForm):
        _translate = QtCore.QCoreApplication.translate
        addForceForm.setWindowTitle(_translate("addForceForm", "Add Force"))
        self.x_component.setPlaceholderText(
            _translate("addForceForm", "X component"))
        self.y_component.setPlaceholderText(
            _translate("addForceForm", "Y component"))
        self.select_joint.setItemText(
            0, _translate("addForceForm", "Select Joint:"))
        self.forceButton.setText(_translate("addForceForm", "Add Force"))
