# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/src/dialogs/addforcequick/addforcequick.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddForceDialog(object):
    def setupUi(self, AddForceDialog):
        AddForceDialog.setObjectName("AddForceDialog")
        AddForceDialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        AddForceDialog.resize(202, 118)
        AddForceDialog.setModal(True)
        self.verticalLayout = QtWidgets.QVBoxLayout(AddForceDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.xComponent = QtWidgets.QLineEdit(parent=AddForceDialog)
        self.xComponent.setObjectName("xComponent")
        self.verticalLayout.addWidget(self.xComponent)
        self.yComponent = QtWidgets.QLineEdit(parent=AddForceDialog)
        self.yComponent.setObjectName("yComponent")
        self.verticalLayout.addWidget(self.yComponent)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.doneButton = QtWidgets.QPushButton(parent=AddForceDialog)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout.addWidget(self.doneButton)
        self.cancelButton = QtWidgets.QPushButton(parent=AddForceDialog)
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(AddForceDialog)
        QtCore.QMetaObject.connectSlotsByName(AddForceDialog)

    def retranslateUi(self, AddForceDialog):
        _translate = QtCore.QCoreApplication.translate
        AddForceDialog.setWindowTitle(_translate("AddForceDialog", "Add Force"))
        self.xComponent.setPlaceholderText(_translate("AddForceDialog", "X Component"))
        self.yComponent.setPlaceholderText(_translate("AddForceDialog", "Y Component"))
        self.doneButton.setText(_translate("AddForceDialog", "Done"))
        self.cancelButton.setText(_translate("AddForceDialog", "Cancel"))
