# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/trusseditor/forms/trusspreferences/trusspreferences.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_trussPreferences(object):
    def setupUi(self, trussPreferences):
        trussPreferences.setObjectName("trussPreferences")
        trussPreferences.resize(440, 301)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            trussPreferences.sizePolicy().hasHeightForWidth())
        trussPreferences.setSizePolicy(sizePolicy)
        trussPreferences.setSizeGripEnabled(False)
        trussPreferences.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(trussPreferences)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=trussPreferences)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.colorLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.colorLabel.setObjectName("colorLabel")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.colorLabel)
        self.jointColorWidget = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.jointColorWidget.sizePolicy().hasHeightForWidth())
        self.jointColorWidget.setSizePolicy(sizePolicy)
        self.jointColorWidget.setMinimumSize(QtCore.QSize(71, 0))
        self.jointColorWidget.setAutoFillBackground(True)
        self.jointColorWidget.setObjectName("jointColorWidget")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.jointColorWidget)
        self.highlightedColorLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.highlightedColorLabel.setObjectName("highlightedColorLabel")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.highlightedColorLabel)
        self.jointFocusedColorWidget = QtWidgets.QWidget(parent=self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.jointFocusedColorWidget.sizePolicy().hasHeightForWidth())
        self.jointFocusedColorWidget.setSizePolicy(sizePolicy)
        self.jointFocusedColorWidget.setMinimumSize(QtCore.QSize(71, 0))
        self.jointFocusedColorWidget.setBaseSize(QtCore.QSize(0, 0))
        self.jointFocusedColorWidget.setAutoFillBackground(True)
        self.jointFocusedColorWidget.setObjectName("jointFocusedColorWidget")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.jointFocusedColorWidget)
        self.radiusDoubleSpinBox = QtWidgets.QDoubleSpinBox(
            parent=self.groupBox)
        self.radiusDoubleSpinBox.setMaximum(9999.0)
        self.radiusDoubleSpinBox.setObjectName("radiusDoubleSpinBox")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.radiusDoubleSpinBox)
        self.radiusLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.radiusLabel.setObjectName("radiusLabel")
        self.formLayout.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.radiusLabel)
        self.gridLayout.addWidget(self.groupBox, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=trussPreferences)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.widthLabel = QtWidgets.QLabel(parent=self.groupBox_2)
        self.widthLabel.setObjectName("widthLabel")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.widthLabel)
        self.widthDoubleSpinBox = QtWidgets.QDoubleSpinBox(
            parent=self.groupBox_2)
        self.widthDoubleSpinBox.setMaximum(9999.0)
        self.widthDoubleSpinBox.setObjectName("widthDoubleSpinBox")
        self.formLayout_2.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.widthDoubleSpinBox)
        self.memberColorLabel = QtWidgets.QLabel(parent=self.groupBox_2)
        self.memberColorLabel.setObjectName("memberColorLabel")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.memberColorLabel)
        self.memberColorWidget = QtWidgets.QWidget(parent=self.groupBox_2)
        self.memberColorWidget.setMinimumSize(QtCore.QSize(71, 0))
        self.memberColorWidget.setBaseSize(QtCore.QSize(0, 0))
        self.memberColorWidget.setAutoFillBackground(True)
        self.memberColorWidget.setObjectName("memberColorWidget")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.memberColorWidget)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(parent=trussPreferences)
        self.groupBox_4.setObjectName("groupBox_4")
        self.formLayout_4 = QtWidgets.QFormLayout(self.groupBox_4)
        self.formLayout_4.setObjectName("formLayout_4")
        self.supportColorLabel = QtWidgets.QLabel(parent=self.groupBox_4)
        self.supportColorLabel.setObjectName("supportColorLabel")
        self.formLayout_4.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.supportColorLabel)
        self.supportColorWidget = QtWidgets.QWidget(parent=self.groupBox_4)
        self.supportColorWidget.setMinimumSize(QtCore.QSize(71, 0))
        self.supportColorWidget.setAutoFillBackground(True)
        self.supportColorWidget.setObjectName("supportColorWidget")
        self.formLayout_4.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.supportColorWidget)
        self.sizeLabel = QtWidgets.QLabel(parent=self.groupBox_4)
        self.sizeLabel.setObjectName("sizeLabel")
        self.formLayout_4.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.sizeLabel)
        self.sizeDoubleSpinBox = QtWidgets.QDoubleSpinBox(
            parent=self.groupBox_4)
        self.sizeDoubleSpinBox.setMaximum(9999.0)
        self.sizeDoubleSpinBox.setObjectName("sizeDoubleSpinBox")
        self.formLayout_4.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.sizeDoubleSpinBox)
        self.gridLayout.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(parent=trussPreferences)
        self.groupBox_3.setObjectName("groupBox_3")
        self.formLayout_3 = QtWidgets.QFormLayout(self.groupBox_3)
        self.formLayout_3.setObjectName("formLayout_3")
        self.forceColorLabel = QtWidgets.QLabel(parent=self.groupBox_3)
        self.forceColorLabel.setObjectName("forceColorLabel")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.forceColorLabel)
        self.forceColorWidget = QtWidgets.QWidget(parent=self.groupBox_3)
        self.forceColorWidget.setMinimumSize(QtCore.QSize(71, 0))
        self.forceColorWidget.setAutoFillBackground(True)
        self.forceColorWidget.setObjectName("forceColorWidget")
        self.formLayout_3.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.forceColorWidget)
        self.headWidthLabel = QtWidgets.QLabel(parent=self.groupBox_3)
        self.headWidthLabel.setObjectName("headWidthLabel")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.headWidthLabel)
        self.headWidthDoubleSpinBox = QtWidgets.QDoubleSpinBox(
            parent=self.groupBox_3)
        self.headWidthDoubleSpinBox.setMaximum(9999.0)
        self.headWidthDoubleSpinBox.setObjectName("headWidthDoubleSpinBox")
        self.formLayout_3.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.headWidthDoubleSpinBox)
        self.headLengthLabel = QtWidgets.QLabel(parent=self.groupBox_3)
        self.headLengthLabel.setObjectName("headLengthLabel")
        self.formLayout_3.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.headLengthLabel)
        self.headLengthDoubleSpinBox = QtWidgets.QDoubleSpinBox(
            parent=self.groupBox_3)
        self.headLengthDoubleSpinBox.setMaximum(9999.0)
        self.headLengthDoubleSpinBox.setObjectName("headLengthDoubleSpinBox")
        self.formLayout_3.setWidget(
            2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.headLengthDoubleSpinBox)
        self.scaleFactorLabel = QtWidgets.QLabel(parent=self.groupBox_3)
        self.scaleFactorLabel.setObjectName("scaleFactorLabel")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.scaleFactorLabel)
        self.scaleFactorDoubleSpinBox = QtWidgets.QDoubleSpinBox(
            parent=self.groupBox_3)
        self.scaleFactorDoubleSpinBox.setMaximum(9999.0)
        self.scaleFactorDoubleSpinBox.setObjectName("scaleFactorDoubleSpinBox")
        self.formLayout_3.setWidget(
            3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.scaleFactorDoubleSpinBox)
        self.gridLayout.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.applyButton = QtWidgets.QPushButton(parent=trussPreferences)
        self.applyButton.setObjectName("applyButton")
        self.gridLayout.addWidget(self.applyButton, 2, 0, 1, 1)
        self.resetButton = QtWidgets.QPushButton(parent=trussPreferences)
        self.resetButton.setObjectName("resetButton")
        self.gridLayout.addWidget(self.resetButton, 2, 1, 1, 1)

        self.retranslateUi(trussPreferences)
        QtCore.QMetaObject.connectSlotsByName(trussPreferences)

    def retranslateUi(self, trussPreferences):
        _translate = QtCore.QCoreApplication.translate
        trussPreferences.setWindowTitle(_translate(
            "trussPreferences", "Truss Preferences"))
        self.groupBox.setTitle(_translate("trussPreferences", "Joints"))
        self.colorLabel.setText(_translate("trussPreferences", "Color"))
        self.highlightedColorLabel.setText(
            _translate("trussPreferences", "Focused Color"))
        self.radiusLabel.setText(_translate("trussPreferences", "Radius"))
        self.groupBox_2.setTitle(_translate("trussPreferences", "Members"))
        self.widthLabel.setText(_translate("trussPreferences", "Width"))
        self.memberColorLabel.setText(_translate("trussPreferences", "Color"))
        self.groupBox_4.setTitle(_translate("trussPreferences", "Supports"))
        self.supportColorLabel.setText(_translate("trussPreferences", "Color"))
        self.sizeLabel.setText(_translate("trussPreferences", "Size"))
        self.groupBox_3.setTitle(_translate("trussPreferences", "Forces"))
        self.forceColorLabel.setText(_translate("trussPreferences", "Color"))
        self.headWidthLabel.setText(
            _translate("trussPreferences", "Head Width"))
        self.headLengthLabel.setText(
            _translate("trussPreferences", "Head Length"))
        self.scaleFactorLabel.setText(
            _translate("trussPreferences", "Scale Factor"))
        self.applyButton.setText(_translate("trussPreferences", "Apply"))
        self.resetButton.setText(_translate("trussPreferences", "Reset"))
