# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/src/dialogs/generalsettings/generalsettings.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_generalSettings(object):
    def setupUi(self, generalSettings):
        generalSettings.setObjectName("generalSettings")
        generalSettings.resize(415, 146)
        self.gridLayout = QtWidgets.QGridLayout(generalSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=generalSettings)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.zoomSensitivityLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.zoomSensitivityLabel.setObjectName("zoomSensitivityLabel")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.zoomSensitivityLabel)
        self.zoomSensitiviySpinBox = QtWidgets.QSpinBox(parent=self.groupBox)
        self.zoomSensitiviySpinBox.setObjectName("zoomSensitiviySpinBox")
        self.formLayout.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.zoomSensitiviySpinBox)
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.zoomStepSpinBox = QtWidgets.QSpinBox(parent=self.groupBox)
        self.zoomStepSpinBox.setObjectName("zoomStepSpinBox")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.zoomStepSpinBox)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.applyButton = QtWidgets.QPushButton(parent=generalSettings)
        self.applyButton.setObjectName("applyButton")
        self.gridLayout.addWidget(self.applyButton, 1, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(parent=generalSettings)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 1, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(parent=generalSettings)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayout_2 = QtWidgets.QFormLayout(self.groupBox_2)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.panButtonSelection = QtWidgets.QComboBox(parent=self.groupBox_2)
        self.panButtonSelection.setObjectName("panButtonSelection")
        self.panButtonSelection.addItem("")
        self.panButtonSelection.addItem("")
        self.formLayout_2.setWidget(
            0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.panButtonSelection)
        self.gridLayout.addWidget(self.groupBox_2, 0, 1, 1, 1)

        self.retranslateUi(generalSettings)
        QtCore.QMetaObject.connectSlotsByName(generalSettings)

    def retranslateUi(self, generalSettings):
        _translate = QtCore.QCoreApplication.translate
        generalSettings.setWindowTitle(_translate(
            "generalSettings", "General Settings"))
        self.groupBox.setTitle(_translate("generalSettings", "Zoom Settings"))
        self.zoomSensitivityLabel.setText(
            _translate("generalSettings", "Zoom Sensitivity"))
        self.label.setText(_translate("generalSettings", "Zoom Step"))
        self.applyButton.setText(_translate("generalSettings", "Apply"))
        self.cancelButton.setText(_translate("generalSettings", "Cancel"))
        self.groupBox_2.setTitle(_translate("generalSettings", "Pan Settings"))
        self.label_2.setText(_translate("generalSettings", "Pan Button"))
        self.panButtonSelection.setItemText(
            0, _translate("generalSettings", "Middle Mouse"))
        self.panButtonSelection.setItemText(
            1, _translate("generalSettings", "Right Mouse"))
