# Form implementation generated from reading ui file '/Users/levirogalla/Dev/Practice/Projects/truss-gui/src/dialogs/generalsettings/generalsettings.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_generalSettings(object):
    def setupUi(self, generalSettings):
        generalSettings.setObjectName("generalSettings")
        generalSettings.resize(400, 115)
        self.gridLayout = QtWidgets.QGridLayout(generalSettings)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=generalSettings)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.zoomSensitivityLabel = QtWidgets.QLabel(parent=self.groupBox)
        self.zoomSensitivityLabel.setObjectName("zoomSensitivityLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.zoomSensitivityLabel)
        self.zoomSensitiviySpinBox = QtWidgets.QSpinBox(parent=self.groupBox)
        self.zoomSensitiviySpinBox.setObjectName("zoomSensitiviySpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.zoomSensitiviySpinBox)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)
        self.applyButton = QtWidgets.QPushButton(parent=generalSettings)
        self.applyButton.setObjectName("applyButton")
        self.gridLayout.addWidget(self.applyButton, 1, 0, 1, 1)
        self.cancelButton = QtWidgets.QPushButton(parent=generalSettings)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 1, 1, 1, 1)

        self.retranslateUi(generalSettings)
        QtCore.QMetaObject.connectSlotsByName(generalSettings)

    def retranslateUi(self, generalSettings):
        _translate = QtCore.QCoreApplication.translate
        generalSettings.setWindowTitle(_translate("generalSettings", "General Settings"))
        self.groupBox.setTitle(_translate("generalSettings", "Settings"))
        self.zoomSensitivityLabel.setText(_translate("generalSettings", "Zoom Sensitivity"))
        self.applyButton.setText(_translate("generalSettings", "Apply"))
        self.cancelButton.setText(_translate("generalSettings", "Cancel"))
